language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
branches:
  only:
    - main
script:
  - npm install -g codecov
  - npm test -- --clearCache
  - npm test -- --coverage
after_script:
  - CODECOV_TOKEN=$CODECOV_TOKEN codecov
