language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
branches:
  only:
    - main
before_install:
  - cd frontend
script:
  - npm install -g codecov
  - npm test -- --clearCache
  - npm test -- --coverage
after_script:
  - CODECOV_TOKEN=$CODECOV_TOKEN codecov
before_deploy:
  - cd frontend
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
