language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
branches:
  only:
    - main
before_install:
  - cd frontend
script:
  - npm install -g codecov
  - npm test -- --clearCache
  - npm test -- --coverage
  - npm run build
after_script:
  - CODECOV_TOKEN=$CODECOV_TOKEN codecov
deploy:
  provider: pages
  script: ls
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: main
after_failure:
  - ls
