export { default as Header } from './header/Header';
export { default as AddRestaurant } from './add-restaurant/AddRestaurant';
export { default as RestaurantList } from './restaurant-list/RestaurantList';
export { default as UpdateRestaurant } from './update-restaurant/UpdateRestaurant';
export { default as ReviewCard } from './review-card/ReviewCard';
export { default as StarRate } from './star-rate/StarRate';
export { default as RestaurantDetails } from './restaurant-details/RestaurantDetails';
export { default as AddReview } from './add-review/AddReview';
export { default as Login } from './login/Login';
