version: '3'
services:
  node-api:
    container_name: api
    read_only: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: api:1.0
    ports:
      - 5000:5000
    restart: always
    volumes:
      - .:/usr/app/api
    env_file:
      - ./.env
