FROM mhart/alpine-node:15.12.0
WORKDIR /usr/app/api
COPY ["package.json", "./"]
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --only=production; \
        fi
RUN npm install
COPY . .
CMD [ "npm", "start"]