export const API_URL = 'http://localhost:5000/api/v1';
export enum ActionType {
  ADD_RESTAURANT = 'ADD_RESTAURANT',
  REMOVE_RESTAURANT = 'REMOVE_RESTAURANT',
  FETCH_RESTAURANTS = 'FETCH_RESTAURANTS',
}
